name: Publish Site
on:
  push:
    branches:
      - 'main'
  workflow_dispatch:
jobs:
  Publish-Site:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Install SSH Key And Test Connection
        run: |
          mkdir -p ~/.ssh/
          install -m 600 -D /dev/null ~/.ssh/id
          echo "${{ secrets.SSH_KEY }}" > ~/.ssh/id
          
          SSH_HOST_PUBLIC_KEY=$(ssh-keyscan -t ed25519 v4.electriclemur.com 2> /dev/null)
          echo "$SSH_HOST_PUBLIC_KEY" >> ~/.ssh/known_hosts

          SSH_HOST_PUBLIC_KEY=$(echo "$SSH_HOST_PUBLIC_KEY" | sed 's/^[a-z0-9\.]* //g')
          echo "{SSH_HOST_PUBLIC_KEY}={${SSH_HOST_PUBLIC_KEY}}" >> $GITHUB_ENV

          SSH_HOST=$(ssh root@v4.electriclemur.com -i ~/.ssh/id "hostname")
          test "$SSH_HOST" = "lemur-web01"
      - name: Create site directory
        run: |
          ssh root@v4.electriclemur.com -i ~/.ssh/id "mkdir -p /volumes/jw_index/site"
      - name: Sync Static Files
        uses: swillner/sftp-sync-action@v1.0
        with:
          server: "v4.electriclemur.com"
          user: "root"
          user_private_key: "${{ secrets.SSH_KEY }}"
          host_public_key: "${{ env.SSH_HOST_PUBLIC_KEY}}"
          local: "./site"
          remote: "/volumes/jw_index/site"
          mirror_options: "--exclude-glob=.git*/ --verbose"
      - name: Update permissions
        run: |
          ssh root@v4.electriclemur.com -i ~/.ssh/id "chmod -R a+r /volumes/jw_index/site"
      - name: Restart container
        run: |
          ssh root@v4.electriclemur.com -i ~/.ssh/id "docker rm -f jw_index 2> /dev/null 1> /dev/null"

          CMD=""
          CMD+="docker run -d --name jw_index --restart=always "
          CMD+="--label 'traefik.enable=true' "
          CMD+="--label 'traefik.http.routers.jw_index.entrypoints=websecure' "
          CMD+="--label 'traefik.http.routers.jw_index.rule=Host(\`jameswilliams.me\`)' "
          CMD+="--label 'traefik.http.routers.jw_index.tls=true' "
          CMD+="--label 'traefik.http.routers.jw_index.tls.certresolver=le' "

          CMD+="--label 'traefik.http.routers.jw_index_redirect.entrypoints=web' "
          CMD+="--label 'traefik.http.routers.jw_index_redirect.rule=Host(\`jameswilliams.me\`)' "
          CMD+="--label 'traefik.http.routers.jw_index_redirect.middlewares=jw_index_redirect' "
          CMD+="--label 'traefik.http.middlewares.jw_index_redirect.redirectscheme.scheme=https' "

          CMD+="-v /volumes/jw_index/site:/usr/share/nginx/html:ro "
          CMD+="nginx:1.21.6-alpine "

          ssh root@v4.electriclemur.com -i ~/.ssh/id "$CMD"


