name: Publish Site
on: [push]
jobs:
  Publish-Site:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Install SSH Key And Test Connection
        run: |
          mkdir -p ~/.ssh/
          install -m 600 -D /dev/null ~/.ssh/id
          echo "${{ secrets.SSH_KEY }}" > ~/.ssh/id
          
          ssh-keyscan -H v4.electriclemur.com >> ~/.ssh/known_hosts

          SSH_HOST=$(ssh root@v4.electriclemur.com -i ~/.ssh/id "hostname")
          test "$SSH_HOST" = "lemur-web01"
      - name: Create site directory
        run: |
          ssh root@v4.electriclemur.com -i ~/.ssh/id "mkdir -p /volumes/jw_index/site"
          ls "${{ github.workspace }}"
      

