name: Publish Site
on: [push]
jobs:
  Publish-Site:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Install SSH Key And Test Connection
        run: |
          mkdir -p ~/.ssh/
          install -m 600 -D /dev/null ~/.ssh/id
          echo "${{ secrets.SSH_KEY }}" > ~/.ssh/id
          
          SSH_HOST_PUBLIC_KEY=$(ssh-keyscan -t ed25519 v4.electriclemur.com 2> /dev/null)
          echo "$SSH_HOST_PUBLIC_KEY" >> ~/.ssh/known_hosts

          SSH_HOST_PUBLIC_KEY=$(echo "$SSH_HOST_PUBLIC_KEY" | sed 's/^[a-z0-9\.]* //g')
          echo "{SSH_HOST_PUBLIC_KEY}={${SSH_HOST_PUBLIC_KEY}}" >> $GITHUB_ENV

          SSH_HOST=$(ssh root@v4.electriclemur.com -i ~/.ssh/id "hostname")
          test "$SSH_HOST" = "lemur-web01"
      - name: Create site directory
        run: |
          ssh root@v4.electriclemur.com -i ~/.ssh/id "mkdir -p /volumes/jw_index/site"
      - name: Sync Static Files
        uses: swillner/sftp-sync-action@v1.0
          server: v4.electriclemur.com
          user: root
          user_private_key: "${{ secrets.SSH_KEY }}"
          host_public_key: "${{ env.SSH_HOST_PUBLIC_KEY}}"
          local: ./site
          remote: /volumes/jw_index/site
          mirror_options: "--exclude-glob=.git*/ --verbose"
      

