name: Publish Site
on: [push]
jobs:
  Publish-Site:
    runs-on: ubuntu-latest
    steps:
      - name: Install SSH Key And Test Connection
        run: |
          mkdir -p ~/.ssh/
          install -m 600 -D /dev/null ~/.ssh/id
          echo "${{ secrets.SSH_KEY }}" > ~/.ssh/id
          
          ssh-keyscan -H v4.electriclemur.com >> ~/.ssh/known_hosts

          ssh root@v4.electriclemur.com "hostname"
